name: build_publish_docker

on:
  workflow_dispatch:
  workflow_run:
    workflows: [ "test_application" ]
    types: [ "completed" ]
    branches: [ "main" ]

jobs:
  docker:
    uses: arraial/workflows/.github/workflows/docker.yml@main
    with:
      image_name: ${{ vars.CONTAINER_TAG }}
    secrets: inherit
    permissions:
      contents: write
      packages: write
