name: test_application

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  python:
    uses: arraial/workflows/.github/workflows/python.yml@main
    secrets: inherit
    with:
      app_name: pipo_hub
    env:
      TEST_RABBITMQ_URL: ${{ secrets.TEST_RABBITMQ_URL }}