name: test_application

on:
  workflow_dispatch:
  push:
    branches: [ "**" ]

jobs:
  python:
    uses: arraial/workflows/.github/workflows/python.yml@0.0.5
    secrets: inherit
    with:
      app_name: ${{ vars.APP_NAME }}
